<?php

declare(strict_types=1);

namespace App\Filament\Resources\PpskGroups\Schemas;

use App\Domain\VlanPlan;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Schema;

// Create/Edit PPSK form, per CLAUDE.md Section 16.3. There is no password
// field on purpose: PSKs are generated by the service (Section 14) and
// shown once after creation. Subnet, tunnel, and gateway are fixed 1:1
// derivations of the VLAN and are shown in the option label, never chosen.
class PpskGroupForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('label')
                    ->label('Label')
                    ->required()
                    ->maxLength(128)
                    ->regex('/^VLAN\d+_[A-Za-z0-9]+$/')
                    ->placeholder('VLAN300_GUESTA')
                    ->helperText('Naming convention: VLAN<id>_<GroupName> (Section 6).'),

                Select::make('vlan_id')
                    ->label('VLAN / tunnel')
                    ->required()
                    ->options(VlanPlan::options())
                    ->helperText('VLAN, subnet, WireGuard tunnel, and gateway are paired 1:1; picking the VLAN picks them all.'),

                Toggle::make('enabled')
                    ->label('Enabled')
                    ->default(true)
                    ->visibleOn('create')
                    ->helperText('Disabled groups cannot authenticate. Toggle later from the list.'),
            ]);
    }
}
